name: Upload dist

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    concurrency:
      group: upload-dist-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Dist
        run: pnpm run build

      - name: Deploy to OSS
        run: pnpm run deploy
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          BUCKET: ${{ secrets.OSS_BUCKET }}

